# KoK3 WE Engine Decompilation - Stub File Creator
# Maps c:\we\trunk\<path> -> src\<path>

$projectRoot = "C:\Users\jo\.gemini\antigravity\scratch\kok3-decomp\src"

# All source file paths from the original binary (relative to c:\we\trunk\)
$files = @(
    "apihackcheck.cpp"
    "audio/caudiobase.cpp"
    "audio/caudiocreate.cpp"
    "audio/caudiomanage.cpp"
    "audio/cezmp3.cpp"
    "audio/csound.cpp"
    "audio/cwavaudio.cpp"
    "buffer/crenderbuffer.cpp"
    "buffer/crenderbuffermanage.cpp"
    "buffer/vertexbufferdx9.cpp"
    "casualgame/cgameddr.cpp"
    "casualgame/gamecolortest.cpp"
    "casualgame/gamememcard.cpp"
    "casualgamelibrary/casualgplatform.h"
    "cgamelanguage.cpp"
    "chatwindow/chatwindow.cpp"
    "cselectplayer.cpp"
    "cworldinfo.cpp"
    "directxclass/diutil.cpp"
    "directxclass/getdxver.cpp"
    "effect/c3dsmaxparticle.cpp"
    "effect/cchaineffect.cpp"
    "effect/cmodeleffect.cpp"
    "filesystemlib/packfileobj.cpp"
    "filesystemlib/stdiofileobj.cpp"
    "gameglobal/cchatlogmanager.cpp"
    "gameglobal/cdoublecastmanager.cpp"
    "gameglobal/cgameglobal.cpp"
    "gameglobal/cpartybuffermanager.cpp"
    "gameglobal/cracecarinfo.cpp"
    "gameglobal/cstaller.cpp"
    "gameglobal/ctransferitem.cpp"
    "gamerecorder/record.cpp"
    "gkk2.cpp"
    "inputcontrol/inputcontrol.cpp"
    "interface/cd3dfont.cpp"
    "interface/cskicontable.cpp"
    "interface/csystemsms.cpp"
    "interface/component/cguibuttonbase.cpp"
    "interface/component/cguicombobox.cpp"
    "interface/component/cguicomponent.cpp"
    "interface/component/cguiedit.cpp"
    "interface/component/cguiedit32.cpp"
    "interface/component/cguieditx.cpp"
    "interface/component/cguiezlayout.cpp"
    "interface/component/cguiinfo.cpp"
    "interface/component/cguilistbox.cpp"
    "interface/component/cguimemo.cpp"
    "interface/component/cguimenu.cpp"
    "interface/component/cguipanelarray.cpp"
    "interface/component/cguiprogressbar.cpp"
    "interface/component/cguireport.cpp"
    "interface/component/cguiscrollbar.cpp"
    "interface/component/cguitrackbar.cpp"
    "interface/component/clayoutpanel.cpp"
    "interface/component/hd/chanchorgroup.cpp"
    "interface/component/hd/chdocument.cpp"
    "interface/component/hd/chparse.cpp"
    "interface/component/hd/chparsebase.cpp"
    "interface/component/hd/chview.cpp"
    "interface/component/hd/chviewkernel.cpp"
    "interface/driver/cguicanvasd3d.cpp"
    "interface/driver/cguicanvasd3d.h"
    "interface/driver/cguifont32.cpp"
    "interface/driver/cguifont32.h"
    "interface/driver/cguilinebreaker.cpp"
    "interface/driver/cguisurface.cpp"
    "interface/driver/cguitexture.cpp"
    "interface/driver/citemtag.cpp"
    "interface/driver/ctexttagmanager.cpp"
    "interface/driver/getfontnamefromfile.cpp"
    "interface/gamefont/gamefontbmp.cpp"
    "interface/gamefont/gamefontcollection.cpp"
    "interface/gamefont/gamefontmanager.cpp"
    "interface/gameui/cdesktopgame.cpp"
    "interface/gameui/cdesktopmain.cpp"
    "interface/gameui/cformarmymanage.cpp"
    "interface/gameui/cformassiststone.cpp"
    "interface/gameui/cformauction.cpp"
    "interface/gameui/cformauction.h"
    "interface/gameui/cformautoskill.cpp"
    "interface/gameui/cformbackpack.cpp"
    "interface/gameui/cformbarracks.cpp"
    "interface/gameui/cformchat.cpp"
    "interface/gameui/cformchatroom.cpp"
    "interface/gameui/cformcountryfunction.cpp"
    "interface/gameui/cformdailyquest.cpp"
    "interface/gameui/cformdebuginfo.cpp"
    "interface/gameui/cformdepot.cpp"
    "interface/gameui/cformdragonbreed.cpp"
    "interface/gameui/cformdragoncrystal.cpp"
    "interface/gameui/cformeqenehase.cpp"
    "interface/gameui/cformequip.cpp"
    "interface/gameui/cformequip.h"
    "interface/gameui/cformequipillusion.cpp"
    "interface/gameui/cformequipmake.cpp"
    "interface/gameui/cformexchange.cpp"
    "interface/gameui/cformfeeling.cpp"
    "interface/gameui/cformforum.cpp"
    "interface/gameui/cformgemmake.cpp"
    "interface/gameui/cformherdmonster.cpp"
    "interface/gameui/cformhero.cpp"
    "interface/gameui/cformheroselect.cpp"
    "interface/gameui/cforminput.cpp"
    "interface/gameui/cformiqtest.cpp"
    "interface/gameui/cformitemgather.cpp"
    "interface/gameui/cformkingdomdata.cpp"
    "interface/gameui/cformkingdompowerset.cpp"
    "interface/gameui/cformladder.cpp"
    "interface/gameui/cformmacroedit.cpp"
    "interface/gameui/cformmail.cpp"
    "interface/gameui/cformmap.cpp"
    "interface/gameui/cformmbuildinglayout.cpp"
    "interface/gameui/cformmissionlist.cpp"
    "interface/gameui/cformmobbook.cpp"
    "interface/gameui/cformmuformmore.cpp"
    "interface/gameui/cformmultiuse.cpp"
    "interface/gameui/cformnewmultiuse.cpp"
    "interface/gameui/cformparty.cpp"
    "interface/gameui/cformpartytask.cpp"
    "interface/gameui/cformpet.cpp"
    "interface/gameui/cformpetendadopt.cpp"
    "interface/gameui/cformprice.cpp"
    "interface/gameui/cformquest.cpp"
    "interface/gameui/cformreward.cpp"
    "interface/gameui/cformroom.cpp"
    "interface/gameui/cformroomlayout.cpp"
    "interface/gameui/cformroulette.cpp"
    "interface/gameui/cformrunbar.cpp"
    "interface/gameui/cformsk.cpp"
    "interface/gameui/cformspctrl.cpp"
    "interface/gameui/cformstallman.cpp"
    "interface/gameui/cformsuitshow.cpp"
    "interface/gameui/cformtankproduce.cpp"
    "interface/gameui/cformtimerecorder.cpp"
    "interface/gameui/cformtooltip.cpp"
    "interface/gameui/cformwarrecord.cpp"
    "interface/gameui/cformwatchplayer.cpp"
    "interface/gameui/cformworldmap.cpp"
    "interface/gameui/cuserinterface.cpp"
    "interface/kernel/cguikernel.cpp"
    "interface/kernel/cguiloader.cpp"
    "interface/kernel/formlist.cpp"
    "interface/kernel/formproperty.cpp"
    "interface/kernel/formtools.cpp"
    "model/canimation.cpp"
    "model/canimationaction.cpp"
    "model/cequipmodel.cpp"
    "model/cequipmodeldb.cpp"
    "model/cmeshmodel.cpp"
    "model/cmeshmodeldb.cpp"
    "model/cmeshserializer.cpp"
    "model/cskeletonhierarchy.cpp"
    "model/cskeletonserializer.cpp"
    "model/cskinnedcharacterequippart.cpp"
    "model/cskinnedcharactermodel.cpp"
    "model/cstop.cpp"
    "model/csubmeshserializer.cpp"
    "model/cthingmesh.cpp"
    "model/cthingmeshdb.cpp"
    "network/beingprotocolmanager.cpp"
    "network/cgamenet.cpp"
    "network/cnetpacket.cpp"
    "network/cnetprotocol.cpp"
    "network/cnetwork.cpp"
    "network/cnetwork.h"
    "network/mudclientfunctions.cpp"
    "network/mudclientfunctions.h"
    "network/muddatamixedtype.cpp"
    "network/mudserverfunctions.cpp"
    "network/netlzss.cpp"
    "network/netpacketv3.cpp"
    "pathfinding/areacellconstructor.cpp"
    "pathfinding/mappathfinding.cpp"
    "pathfinding/wowopathfinding.cpp"
    "playerprop/cactionitem.cpp"
    "playerprop/cautoskillmanager.cpp"
    "playerprop/cbaseitem.cpp"
    "playerprop/cbeingprop.cpp"
    "playerprop/cchatroommaster.cpp"
    "playerprop/cdance.cpp"
    "playerprop/cemotionitem.cpp"
    "playerprop/ceqsuititem.cpp"
    "playerprop/cequipment.cpp"
    "playerprop/cfamilyjoin.cpp"
    "playerprop/cfamilypost.cpp"
    "playerprop/cfamilypostdata.cpp"
    "playerprop/cfurniture.cpp"
    "playerprop/cherolog.cpp"
    "playerprop/chotkey.cpp"
    "playerprop/ckillmobexpmanager.cpp"
    "playerprop/cmacroitem.cpp"
    "playerprop/cmacrolist.cpp"
    "playerprop/cmaillist.cpp"
    "playerprop/cparty.cpp"
    "playerprop/cpktype.cpp"
    "playerprop/cpropsideline.cpp"
    "playerprop/cpropskills.cpp"
    "playerprop/cpropskills.h"
    "playerprop/cquestlog.cpp"
    "playerprop/cquestlog.h"
    "playerprop/craceitem.cpp"
    "playerprop/crelapeople.cpp"
    "playerprop/crelation.cpp"
    "playerprop/crelation.h"
    "playerprop/cskillset.cpp"
    "playerprop/cskillstatus.cpp"
    "playerprop/ctanklist.cpp"
    "playerprop/ctargetitem.cpp"
    "playerprop/ctimeitem.cpp"
    "playerprop/cwarstate.cpp"
    "playerprop/daemonpet.cpp"
    "playerprop/daemonpetaimode.cpp"
    "playerprop/specialskill/cspskill.cpp"
    "portrait/portraitmanager.cpp"
    "scene/beingnametag.cpp"
    "scene/c3dsmaxparticlerender.cpp"
    "scene/cafterimage.cpp"
    "scene/cbeing.cpp"
    "scene/cbeing.h"
    "scene/cbeingdb.cpp"
    "scene/cbeingrender.cpp"
    "scene/cbeingtalktagtexturemanager.cpp"
    "scene/ccliffrender.cpp"
    "scene/cd3dbillboard.cpp"
    "scene/cdecalmapmanager.cpp"
    "scene/cdecalrender.cpp"
    "scene/cdistrender.cpp"
    "scene/cequipphotomanager.cpp"
    "scene/cequiprender.cpp"
    "scene/cfnlabor.h"
    "scene/cfogmanage.cpp"
    "scene/cgametimer.cpp"
    "scene/cheathazemanager.cpp"
    "scene/clightdata.cpp"
    "scene/clightmanage.cpp"
    "scene/clights.cpp"
    "scene/cmaterialanimator.h"
    "scene/cqtree.cpp"
    "scene/crender.cpp"
    "scene/cscene.cpp"
    "scene/cshorewaverender.cpp"
    "scene/cskydomecloud.cpp"
    "scene/cstatusscreeneffect.cpp"
    "scene/cthing.cpp"
    "scene/cthingdb.cpp"
    "scene/ctreasuremanager.cpp"
    "scene/cwaterrender.cpp"
    "scene/cweathersystem.cpp"
    "scene/dpatkctrl.cpp"
    "scene/hurtdigits.cpp"
    "scene/hurtdigits.h"
    "scene/imanualprimitivesrender.h"
    "scene/ipaperdoll.cpp"
    "scene/primitiverendersfactory.cpp"
    "scene/thingfloormesh.cpp"
    "scriptingmodules/cscriptbindingcommon.cpp"
    "scriptingmodules/cscriptmodule.cpp"
    "shader/ceffectshader.cpp"
    "shader/csimhdr.cpp"
    "share/bclasses.cpp"
    "share/cffieldmanage.cpp"
    "share/cfilefield.cpp"
    "share/cloginsetting.cpp"
    "share/cobserver.cpp"
    "share/ctools.cpp"
    "share/ctpool.h"
    "share/cxmlonlpq.cpp"
    "share/hashmap.cpp"
    "share/nhelper/btlist.cpp"
    "share/nhelper/btstream.cpp"
    "share/nhelper/cbasereader.cpp"
    "share/nhelper/cfont32.cpp"
    "share/nhelper/ezstring.cpp"
    "share/nhelper/nhelper.cpp"
    "share/tinyxmlonlpq.cpp"
    "speedtreert/commonsource/idvdirectx9.h"
    "speedtreert/commonsource/idvgeometrybuffer.cpp"
    "speedtreert/commonsource/idvgeometrybuffer.h"
    "speedtreert/commonsource/idvmaterial.h"
    "speedtreert/commonsource/idvshadermanager.cpp"
    "speedtreert/commonsource/idvstate.cpp"
    "speedtreert/commonsource/idvtexture.cpp"
    "speedtreert/commonsource/idvtexture.h"
    "speedtreert/commonsource/speedtreecullengine.cpp"
    "speedtreert/commonsource/speedtreecullengine.h"
    "speedtreert/commonsource/speedtreeforest.cpp"
    "speedtreert/commonsource/speedtreeinstance.cpp"
    "speedtreert/commonsource/speedtreeinstance.h"
    "speedtreert/commonsource/speedtreewrapper.cpp"
    "speedtreert/commonsource/speedtreewrapper.h"
    "speedtreert/commonsource/speedwind2.h"
    "speedtreert/include/speedtreememory.h"
    "terrain/cdistrict.cpp"
    "terrain/clifftable.cpp"
    "terrain/cmbuilding.cpp"
    "terrain/cmterritory.cpp"
    "terrain/cterrain.cpp"
    "terrain/terrainimporter.cpp"
    "terrain/terrainmeshgridnode.cpp"
    "terrain/terrainshadowmap.cpp"
    "terrain/terrainstoppoint.cpp"
    "texture/ctexture.cpp"
    "texture/cwater.cpp"
    "texturecache.cpp"
    "thread/cjobmanager.cpp"
)

$cppCount = 0
$hCount = 0
$dirSet = @{}

foreach ($file in $files) {
    $fullPath = Join-Path $projectRoot $file.Replace("/", "\")
    $dir = Split-Path $fullPath -Parent
    
    # Track unique directories
    if (-not $dirSet.ContainsKey($dir)) {
        $dirSet[$dir] = $true
    }
    
    # Create directory if needed
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    
    $originalPath = "c:\we\trunk\$file"
    
    if ($file.EndsWith(".h")) {
        $content = @"
// [Original path: $originalPath]
// Status: Not started
// This file is part of the King of Kings 3 (WE Engine) decompilation project.

#pragma once

// TODO: Decompile this file
"@
        $hCount++
    } else {
        $content = @"
// [Original path: $originalPath]
// Status: Not started
// This file is part of the King of Kings 3 (WE Engine) decompilation project.

// TODO: Decompile this file
"@
        $cppCount++
    }
    
    Set-Content -Path $fullPath -Value $content -Encoding UTF8
}

Write-Host ""
Write-Host "=== KoK3 WE Engine Decompilation - Stub Creation Complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "Project root: $projectRoot" -ForegroundColor Cyan
Write-Host "Directories created: $($dirSet.Count)" -ForegroundColor Yellow
Write-Host "C++ files (.cpp) created: $cppCount" -ForegroundColor Yellow
Write-Host "Header files (.h) created: $hCount" -ForegroundColor Yellow
Write-Host "Total files created: $($cppCount + $hCount)" -ForegroundColor Yellow
Write-Host ""
